import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Nav from "./components/nav";
import Hydrate from "./components/Hydrate";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //fetch the session
  const session = await getServerSession(authOptions);
  // console.log(session);
  return (
    <html lang="en">
      <body className={`mx-10`}>
        <Hydrate>
          <Nav user={session?.user} expires={session?.expires!} />

          {children}
        </Hydrate>
      </body>
    </html>
  );
}
